jms_serializer:
  handlers:
    datetime:
      default_format: "Y-m-d\\TH:i:sP"
      default_timezone: "UTC"
  visitors:
    json_serialization:
      options:
        - JSON_UNESCAPED_SLASHES
        - JSON_UNESCAPED_UNICODE
        - JSON_PRETTY_PRINT
