nelmio_api_doc:
  documentation:
    info:
      title: RATP REST API
      version: 4.0.1
  areas:
    path_patterns:
      - ^/traffic
      - ^/lines
      - ^/stations
      - ^/destinations
      - ^/missions
      - ^/schedules
