preset: symfony
enabled:
  - concat_with_spaces
  - group_import
disabled:
  - concat_without_spaces
  - no_superfluous_phpdoc_tags_symfony
  - unalign_double_arrow
  - unalign_equals
  - yoda_style

finder:
  exclude: [ var ]
