documentation:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/%prefix%/documentation"
    schemes:  ["%schemes%"]

app:
    type:     annotation
    resource: "@ApiBundle/Controller/CoreController.php"
    schemes:  ["%schemes%"]
    prefix:   "/%prefix%/"

traffic:
    type:     rest
    resource: "@ApiBundle/Controller/TrafficController.php"
    schemes:  ["%schemes%"]
    prefix:   "/%prefix%/"

lines:
    type:     rest
    resource: "@ApiBundle/Controller/LinesController.php"
    schemes:  ["%schemes%"]
    prefix:   "/%prefix%/"

stations:
    type:     rest
    resource: "@ApiBundle/Controller/StationsController.php"
    schemes:  ["%schemes%"]
    prefix:   "/%prefix%/"

destinations:
    type:     rest
    resource: "@ApiBundle/Controller/DestinationsController.php"
    schemes:  ["%schemes%"]
    prefix:   "/%prefix%/"

schedules:
    type:     rest
    resource: "@ApiBundle/Controller/SchedulesController.php"
    schemes:  ["%schemes%"]
    prefix:   "/%prefix%/"