documentation:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /documentation
    schemes:  ["%schemes%"]

app:
    type:     annotation
    resource: "@ApiBundle/Controller/HomeController.php"
    schemes:  ["%schemes%"]

traffic:
    type:     rest
    resource: "@ApiBundle/Controller/TrafficController.php"
    schemes:  ["%schemes%"]