services:
  # CORE SERVICES
  api.storage:
    class: ApiBundle\Services\Core\StorageService
    arguments: ["@request_stack"]
    calls:
      - [ addService, [ 'cache', '@cache.app' ] ]

  # API SERVICES
  api.traffic:
    class: ApiBundle\Services\Api\TrafficService
    calls:
      - [ addService, [ 'storage', '@api.storage' ] ]